### ISSUE TITLE
[NEW ABBREVIATIONS]

### ISSUE THREAD

**Issue by TreciaKS** [Njong392/Abbreve#116]
### Description

To add new abbreviation such as:
-  ily
- bts
- dyk
- gtg
- lmao

**Comment by Njong392** [comment]
Should I assign you to this @TreciaKS ?

**Comment by TreciaKS** [comment]
Yes yes yes 🙌

**Comment by Njong392** [comment]
Hello @TreciaKS this project has been updated a lot since after you created this issue. Please sync your fork with this upstream repo and read the README again to see how the project now stores abbreviations. We already have entries for everything on this list except `dyk` and `bts` Do you still wish to work on it?

**Comment by TreciaKS** [comment]
Yes I do. Will do so and create a PR tomorrow
