### ISSUE TITLE
Get started button not keyboard accessible

### ISSUE THREAD

**Issue by EmmaDawsonDev** [Njong392/Abbreve#125]
### Description

The 'Get Started' button in the header is not reachable by keyboard when tabbing through the site.

### Additional information

I would like to work on this issue.

**Comment by adropofilm** [comment]
Nice catch, assigned you to it @EmmaDawsonDev!

**Comment by Njong392** [comment]
If you check #122 I was debating on removing the component completely since the form component was moved upward.

**Comment by EmmaDawsonDev** [comment]
Ah ok. I've been looking at the component and it turns out the scroll library you're using is completely inaccessible and it's going to take some hacky solutions to work around it. My suggestion would be to at least remove the scroll library and find another way to add scroll animations (I'm pretty sure smooth scrolling in CSS would be enough). I'll hold off on fixing this until you decide what you want to do with the component.

**Comment by Njong392** [comment]
The `react-scroll` library does bring along challenges. Even styling can be hard. So, the form component used to be at the bottom of the page, and the user sort of needed the scroll effect to reach it. But since we have sort of refactored and brought the form closer to the navbar, I see no reason for the scroll effect. Hence no use for these buttons or the library itself.

**Comment by EmmaDawsonDev** [comment]
Ok, I removed the scroll.link and replaced it with a regular one. No worries if you decide to remove the button altogether though :) I'll do some more a11y testing and find some other things to fix :D
